### PR TITLE
Digital Expense Logging

### PR DESCRIPTION
**Pull request by justetz**
See #58 for details. This change will require the following SQL query to be run on any existing databases:

```sql
ALTER TABLE `offices` 
ADD COLUMN `expense_limit` DOUBLE NOT NULL DEFAULT 0
AFTER `nominations_required`;
```

### CODE REVIEW

**Comment by justetz** [comment]
Pulling the latest changes, and then I'll resubmit the PR.

**Comment by draab** [comment]
Actually, you can take your time with this since I don't want to release this for this elections cycle. It would confuse too many people to switch to this system midway through the process.

**Comment by justetz** [comment]
Fair, then I'll work on expanding it further. Ideally, it would be great if all the forms could be digitized, or at least visible online.

**Comment by draab** [comment]
I'll create a new issue for that :)

**Pull request closed without merging**
